DROP TABLE IF EXISTS reservations;

CREATE TABLE reservations
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource     VARCHAR(64),
    user_name    VARCHAR(250),
    start        TIMESTAMP,
    duration     INTEGER
);
