DROP TABLE IF EXISTS reservations;

CREATE TABLE reservations
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource     VARCHAR(64),
    user_name    VARCHAR(250),
    start        TIMESTAMP,
    duration     INTEGER
);

INSERT INTO reservations(resource, user_name, start, duration) VALUES ('DOCTOR', 'Ivan', timestamp '2021-10-25 12:00', 900);
INSERT INTO reservations(resource, user_name, start, duration) VALUES ('MFC', 'Denis', timestamp '2021-10-25 10:30', 180);
INSERT INTO reservations(resource, user_name, start, duration) VALUES ('MAIL_POST', 'Anna', timestamp '2021-10-27 13:20', 30);
INSERT INTO reservations(resource, user_name, start, duration) VALUES ('MFC', 'Elena', timestamp '2021-10-30 18:00', 60);